package peerProcess;

/**
 *
 */
enum eSocketReturns
{
    E_SOCRET_UNKNOWN,
    E_SOCRET_FAILED,
    E_SOCRET_SUCCESS,
    E_SOCRET_IOBLOCK,
    E_SOCRET_NOTHING_TO_READ,
    E_SOCRET_NOTOPEN,
    E_SOCRET_PRECLOSED,
    E_SOCRET_IO_EXCEPTION,
}