/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package peerProcess

import spock.lang.Specification

class AppTest extends Specification {
    def "application has a greeting"() {
        setup:
        def app = new peerProcess()

        when:
        def result = app.greeting

        then:
        result != null
    }

    def "Logger initialization"() {

        given: "An instance of logger and a known ID"
        Logger logr = new Logger(101)

        when:
        def ret = logr.Initialize()

        then:
        ret == 1
            
    }
}
